spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
server:
  servlet:
    session:
      timeout: 60s
      cookie:
        max-age: 60s
        name: SPRING_SESSION_REDIS_SECURITY
