spring:
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/tmp/h2_jpa_groovy_db1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
