spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  output:
    ansi:
      enabled: always
server:
  error:
#    path: /error
    include-exception: true
    include-message: always
    include-stacktrace: always

