spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres-db
    username: sa
    password: passwd
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  output:
    ansi:
      enabled: always
