spring:
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
#      cache:
#        cachecontrol:
#          max-age: 1h
logging:
  level:
    org.springframework.web.servlet.mvc.WebContentInterceptor: trace
