server:
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
logging:
  level:
    org.springframework.context.support.DefaultLifecycleProcessor: trace
management:
  endpoint:
    health:
      probes:
        enabled: true
