server:
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  output:
    ansi:
      enabled: always
logging:
  level:
    org:
      springframework:
        context:
          support:
            DefaultLifecycleProcessor: trace
