server:
  http2:
    enabled: true
  port: 8443
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: hirakida
    key-alias: tomcat
    key-store-type: PKCS12
spring:
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
