spring:
  output:
    ansi:
      enabled: always

app.message: default message

---
spring:
  config:
    activate:
      on-profile: dev

app.message: dev message

---
spring:
  config:
    activate:
      on-profile: production

app.message: production message
