spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  output:
    ansi:
      enabled: always
server:
  servlet:
    session:
      cookie:
        max-age: 60s
        name: SPRING_SESSION_REDIS
        http-only: true
        secure: false
      timeout: 60s
