spring:
  profiles:
    active: h2
  datasource:
    initialization-mode: always
    sql-script-encoding: UTF-8
    #    schema: classpath:db/schema-${spring.datasource.platform}.sql
    #    data: classpath:db/data-${spring.datasource.platform}.sql
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always

---

spring:
  profiles: h2
  datasource:
    platform: h2
    url: jdbc:h2:mem:h2-db
    username: sa
    password:
  h2:
    console:
      enabled: true
#      path: h2-console

---

spring:
  profiles: hsqldb
  datasource:
    platform: hsqldb
    url: jdbc:hsqldb:mem:hsqldb-db
    username: sa
    password:

---

spring:
  profiles: mysql
  datasource:
#    platform: mysql
    url: jdbc:mysql://localhost:3306/jpa_demo
    username: root
    password:

---

spring:
  profiles: postgresql
  datasource:
#    platform: postgresql
    url: jdbc:postgresql://localhost:5432/postgres
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
