spring:
  datasource:
    url: jdbc:h2:mem:graphql-db;NON_KEYWORDS=USER
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
  output:
    ansi:
      enabled: always
