security:
  oauth2:
    client:
      client-id: #####
      client-secret: #####
      client-authentication-scheme: form
      user-authorization-uri: https://access.line.me/dialog/oauth/weblogin
      access-token-uri: https://api.line.me/v2/oauth/accessToken
#      user-authorization-uri: https://access.line.me/oauth2/v2.1/authorize
#      access-token-uri: https://api.line.me/oauth2/v2.1/token
    resource:
      user-info-uri: https://api.line.me/v2/profile
spring:
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
