spring:
  datasource:
    url: jdbc:h2:mem:jpa-db;NON_KEYWORDS=USER
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
  output:
    ansi:
      enabled: always
logging:
  level:
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
