spring:
  datasource:
    initialization-mode: always
    sql-script-encoding: UTF-8
    #    schema: classpath:db/schema-${spring.datasource.platform}.sql
    #    data: classpath:db/data-${spring.datasource.platform}.sql
    url: jdbc:h2:mem:h2-db
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  output:
    ansi:
      enabled: always
logging:
  level:
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
