spring:
  datasource:
    url: jdbc:h2:mem:h2-db
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  output:
    ansi:
      enabled: always
logging:
  level:
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
