package com.example.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.service.Contact;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@EnableSwagger2
@Configuration
public class SwaggerConfig {

    @Bean
    public Docket docket() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .paths(PathSelectors.ant("/users/**"))
                .build()
                .apiInfo(apiInfo());
    }

    private static ApiInfo apiInfo() {
        return new ApiInfoBuilder()
                .title("API Reference")
                .description("This API reference is generated by Swagger2.")
                .version("1.0")
                .license("license v1.0")
                .licenseUrl("http://localhost:8080/license")
                .termsOfServiceUrl("http://localhost:8080/terms")
                .contact(new Contact("contact name",
                                     "http://localhost:8080/contact",
                                     "contact@example.com"))
                .build();
    }
}
