spring:
  datasource:
    initialization-mode: always
    sql-script-encoding: UTF-8
  r2dbc:
    url: r2dbc:h2:mem:///r2dbc-db?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    pool:
      initial-size: 10
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
logging:
  level:
    org.springframework.data.r2dbc.connectionfactory.R2dbcTransactionManager: DEBUG
