spring:
  datasource:
    initialization-mode: always
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:h2-db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jmx:
    enabled: true
  output:
    ansi:
      enabled: always
server:
  tomcat:
    mbeanregistry:
      enabled: true
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#      probes:
#        enabled: true
  health:
    probes:
      enabled: true

info:
  app:
    encoding: UTF-8
    java:
      source: 11
      target: 11
