spring:
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:/mybatis_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  output:
    ansi:
      enabled: always
mybatis:
  configuration:
    map-underscore-to-camel-case: true
