spring:
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/mybatis_demo
    username: user
    password: pass
  output:
    ansi:
      enabled: always
mybatis:
  configuration:
    map-underscore-to-camel-case: true
