spring:
  output:
    ansi:
      enabled: always
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: info, health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
info:
  app:
    java:
      source: 17
      target: 17
