spring:
# UTF-8のCharacterEncodingFilterが自動で適用される
#  http:
#    encoding:
#      enabled: true
#      charset: UTF-8
  thymeleaf:
    cache: false

# 組み込みTomcatのuri-encodingのdefault値はUTF-8
#server:
#  tomcat:
#    uri-encoding: UTF-8
