spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:h2-db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  output:
    ansi:
      enabled: always
server:
  tomcat:
    mbeanregistry:
      enabled: true
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: prometheus, metrics
