spring:
  output:
    ansi:
      enabled: always
server:
  tomcat:
    mbeanregistry:
      enabled: true
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: prometheus, metrics
