spring:
  output:
    ansi:
      enabled: always
server:
  tomcat:
    mbeanregistry:
      enabled: true
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: prometheus, metrics
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true
          base-url: http://localhost:9091
          job: pushgateway-demo
          grouping-key:
            key1: value1
          shutdown-operation: put
