spring:
# UTF-8のCharacterEncodingFilterが自動で適用される
#  http:
#    encoding:
#      enabled: true
#      charset: UTF-8
  thymeleaf:
    cache: false

server:
# 組み込みTomcatのuri-encodingのdefault値はUTF-8
#  tomcat:
#    uri-encoding: UTF-8
  error:
    include-stacktrace: always
