server:
  http2:
    enabled: true
  port: 8443
  ssl:
    certificate: classpath:localhost.pem
    certificate-private-key: classpath:localhost-key.pem
spring:
  output:
    ansi:
      enabled: always
