CREATE TABLE IF NOT EXISTS `user` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `gender` VARCHAR(10) NOT NULL,
  `card` VARCHAR(10) DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
);
