spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:doma-db
    username: sa
    password:
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
doma:
  dialect: h2
