spring:
  session:
    store-type: jdbc
  datasource:
    initialization-mode: always
    sql-script-encoding: UTF-8
    schema: classpath:org/springframework/session/jdbc/schema-h2.sql
    url: jdbc:h2:mem:spring-session-jdbc;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  output:
    ansi:
      enabled: always
server:
  servlet:
    session:
      cookie:
        max-age: 60s
        name: SPRING_SESSION_JDBC
        http-only: true
        secure: false
      timeout: 60s
