spring:
  datasource:
    sql-script-encoding: UTF-8
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:mem:h2-db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
