spring:
  application:
    name: spring-cloud-sleuth-demo
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
