spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:jdbc-db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
