spring:
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/tmp/h2_jdbc_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
