spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
server:
  error:
    whitelabel:
      enabled: false
