spring:
  datasource:
    initialization-mode: always
    sql-script-encoding: UTF-8
    url: jdbc:mysql://localhost:3306/jpa_demo
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
