server:
  port: 7000
spring:
  rsocket:
    server:
      address: localhost
      port: 7000
      mapping-path: /rsocket
      transport: websocket
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
