spring:
  cache:
    cache-names: cache1
  output:
    ansi:
      enabled: always
logging:
  level:
    org.springframework.cache: trace
management:
  endpoints:
    web:
      exposure:
        include: caches, prometheus, metrics
