spring:
  output:
    ansi:
      enabled: always
management:
  info:
    git:
      mode: full
info:
  app:
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8

#endpoints:
#  info:
#    sensitive: false
