server:
  port: 8081
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
  output:
    ansi:
      enabled: always
logging:
  level:
    org.springframework.cache: trace
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
