spring:
  datasource:
    url: jdbc:h2:mem:jdbc-db;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=user
    username: sa
    password:
  sql:
    init:
      encoding: utf-8
  output:
    ansi:
      enabled: always
logging:
  level:
    com.zaxxer.hikari: debug
