services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mysql-db
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
