spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxxxxxxx@gmail.com
    password: xxxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  output:
    ansi:
      enabled: always
