spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:graphql_db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
