management:
  context-path: /actuator
  security:
    enabled: false
security:
  basic:
    enabled: false

spring:
  application:
    name: metorics-demo
  metrics:
    export:
      redis:
        prefix: metrics.mysystem.${spring.application.name:application}.${random.value:0000}
        key:  keys.metrics.mysystem
