spring:
  datasource:
    url: jdbc:h2:mem:graphql_db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  graphql:
    schema-location: classpath:/schema/schema.graphqls
  output:
    ansi:
      enabled: always
