spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:mybatis-db
    username: sa
    password:
  output:
    ansi:
      enabled: always
logging:
  level:
    com.example.mapper: debug
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
