spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:file:/tmp/groovy_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  groovy:
    template:
      check-template-location: false
  output:
    ansi:
      enabled: always
