spring:
  datasource:
    sql-script-encoding: UTF-8  # SQLファイルの文字コード
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/tmp/h2_jdbc_db1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
