spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:batch-chunk;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    job:
      enabled: false
  task:
    scheduling:
      pool:
        size: 10
  output:
    ansi:
      enabled: always
