spring:
  datasource:
    url: jdbc:h2:mem:batch-chunk;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    job:
      enabled: false
  output:
    ansi:
      enabled: always

management:
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: true
          base-url: http://localhost:9091
          job: batch-chunk-demo
          shutdown-operation: push
