spring:
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:transaction_db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
logging:
  level:
#    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
