spring:
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/tmp/h2_batch_chunk_db1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    job:
      enabled: false
