spring:
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:mem:h2-db
    username: sa
    password:
    hikari:
      maximum-pool-size: 1
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
