spring:
  mvc:
    async:
      request-timeout: 5s
  output:
    ansi:
      enabled: always
#  task:
#    execution:
#      pool:
#        core-size: 5
#        max-size: 10
#        queue-capacity: 10
#        keep-alive: 60s
#      thread-name-prefix: task-execution-
