spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always
server:
  servlet:
    session:
      timeout: 60s
