server:
  port: 8082
spring:
  rsocket:
    server:
      address: localhost
      port: 7000
      transport: tcp
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
logging:
  level:
    io.rsocket.FrameLogger: DEBUG
