version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.6.2
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
volumes:
  es_data:
    driver: local
