version: "3"
services:
  elasticsearch:
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
  kibana:
    image: kibana
    ports:
      - "5601:5601"
volumes:
  es_data:
    driver: local
