spring:
  zipkin:
    base-url: http://localhost:9411
    service:
      name: server3
  sleuth:
    sampler:
      probability: 1.0
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
server:
  port: 8082
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.web.client.RestTemplate: debug
