spring:
  datasource:
    initialization-mode: always
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:mvcfn-h2-db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
