spring:
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flyway_demo
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  output:
    ansi:
      enabled: always
