spring:
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/demo
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  output:
    ansi:
      enabled: always
