spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_demo
    username: user
    password: pass
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  output:
    ansi:
      enabled: always
