spring:
  datasource:
#    initialize: false
    sql-script-encoding: UTF-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/tmp/h2_jpa_db1
#    driver-class-name: org.hsqldb.jdbcDriver
#    url: jdbc:hsqldb:file:/tmp/hsqldb_jpa_db1
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/jpa_demo
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
    username: sa
    password:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
#    tomcat:
#      max-active: 20
#      max-idle: 10
#      min-idle: 5
#      initial-size: 1
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
