spring:
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/tmp/h2_mybatis_db2;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  output:
    ansi:
      enabled: always
mybatis:
  config-location: classpath:/mybatis-config.xml
