server:
  port: 8443
  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: hirakida
#    key-alias: tomcat
#    key-store-type: PKCS12
    certificate: classpath:localhost.pem
    certificate-private-key: classpath:localhost-key.pem
spring:
  output:
    ansi:
      enabled: always
