server:
  port: 8081
spring:
  rsocket:
    server:
      address: localhost
      mapping-path: /rsocket
      transport: websocket
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
logging:
  level:
    io.rsocket.FrameLogger: DEBUG
