spring:
  output:
    ansi:
      enabled: always
jasypt:
  encryptor:
    password: password
    algorithm: PBEWITHHMACSHA512ANDAES_256

encrypted:
  message: ENC(ZhfyMMy0kBwESYWDQ5LhD6zMpVAjGqe3hoog4kPGrjpRIBfPPzWg8Ai5qF8mS7CZ)
