spring:
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/tmp/h2_jpa_db4
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:h2:file:/tmp/h2_jpa_db4
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
