CREATE TABLE IF NOT EXISTS user (
  id INT PRIMARY KEY IDENTITY,
  name VARCHAR(30) NOT NULL,
  enabled BOOLEAN DEFAULT FALSE NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL
);
