spring:
  datasource:
    url: jdbc:h2:mem:graphql_db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  output:
    ansi:
      enabled: always
graphql:
  graphiql:
    enabled: true
  voyager:
    enabled: true
