spring:
  task:
    scheduling:
      thread-name-prefix: scheduling-
      pool:
        size: 2
      shutdown:
        await-termination: true
  output:
    ansi:
      enabled: always
management:
  endpoints:
    web:
      exposure:
        include: [scheduledtasks]

cron:
  once_a_minute: 0 * * * * *
