spring:
  output:
    ansi:
      enabled: always
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  app:
    encoding: UTF-8
    java:
      source: 11
      target: 11
