spring:
  session:
    store-type: none
  output:
    ansi:
      enabled: always
server:
  servlet:
    session:
      timeout: 60s
      cookie:
        max-age: 60s
        name: SPRING_SESSION_NONE
        http-only: true
