security:
  oauth2:
    client:
      client-id: #####
      client-secret: #####
      client-authentication-scheme: form
      user-authorization-uri: https://github.com/login/oauth/authorize
      access-token-uri: https://github.com/login/oauth/access_token
    resource:
      user-info-uri: https://api.github.com/user
spring:
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
