spring:
  datasource:
    initialization-mode: always
    sql-script-encoding: UTF-8
    #    schema: classpath:db/schema-${spring.datasource.platform}.sql
    #    data: classpath:db/data-${spring.datasource.platform}.sql
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:mem:h2-db
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
