spring:
  application:
    name: batch-demo
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:dataflow_batch_db
    username: sa
    password:
  batch:
    job:
      enabled: false
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
