server:
  port: 8081
spring:
  kafka:
#    bootstrap-servers: localhost:9092
    template:
      default-topic: topic1
    listener:
      concurrency: 5
    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.example.consumer.UserJsonDeserializer
      group-id: group1
      auto-offset-reset: earliest
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
