spring:
  session:
    store-type: mongodb
  output:
    ansi:
      enabled: always
server:
  servlet:
    session:
      cookie:
        max-age: 60s
        name: SPRING_SESSION_MONGODB
        http-only: true
        secure: false
      timeout: 60s
