spring:
  datasource:
    url: jdbc:h2:mem:spring-session-jdbc;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always
server:
  servlet:
    session:
      cookie:
        max-age: 60s
        name: SPRING_SESSION_JDBC
        http-only: true
        secure: false
      timeout: 60s
