spring:
  datasource:
    initialization-mode: always
    sql-script-encoding: UTF-8
    schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
    url: jdbc:mysql://127.0.0.1:3307/session_jdbc_demo?characterEncoding=utf8&useSSL=false
    username: mysql
    password: password
  session:
    store-type: jdbc
  output:
    ansi:
      enabled: always
server:
  servlet:
    session:
      cookie:
        max-age: 60s
        name: SPRING_SESSION_JDBC
        http-only: true
        secure: false
      timeout: 60s
