spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: xxxxxxxx
            client-secret: xxxxxxxx
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always
