spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:data-rest-db
    username: sa
    password:
  data:
    rest:
      base-path: /
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  output:
    ansi:
      enabled: always
