spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:rest-db;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER
    username: sa
    password:
  data:
    rest:
      base-path: /
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  output:
    ansi:
      enabled: always
