DELETE FROM `person`;
INSERT INTO `person`( name, created_at, updated_at) VALUES ( 'user1', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO `person`( name, created_at, updated_at) VALUES ( 'user2', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO `person`( name, created_at, updated_at) VALUES ( 'user3', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO `person`( name, created_at, updated_at) VALUES ( 'user4', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO `person`( name, created_at, updated_at) VALUES ( 'user5', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO `person`( name, created_at, updated_at) VALUES ( 'user6', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO `person`( name, created_at, updated_at) VALUES ( 'user7', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO `person`( name, created_at, updated_at) VALUES ( 'user8', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO `person`( name, created_at, updated_at) VALUES ( 'user9', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO `person`( name, created_at, updated_at) VALUES ( 'user10', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
