spring:
  kafka:
    #    bootstrap-servers: localhost:9092
    template:
      default-topic: topic1
    producer:
      #      bootstrap-servers: localhost:9092
      value-serializer: com.example.UserJsonSerializer
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
