spring:
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/tmp/h2_scala_db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
