server:
  port: 8443
  ssl:
    enabled: true
#    enabled-protocols: [TLSv1.2]
    key-store: keystore.p12
    key-store-password: xxxxxx
    key-alias: tomcat
    key-store-type: PKCS12
spring:
  devtools:
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always
