spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:/mybatis_db
    username: sa
    password:
  output:
    ansi:
      enabled: always
mybatis:
  configuration:
    map-underscore-to-camel-case: true
