spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: pass
      authentication-database: admin
  output:
    ansi:
      enabled: always
management:
  endpoints:
    web:
      exposure:
        include: prometheus
