spring:
  output:
    ansi:
      enabled: always
management:
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: true
          base-url: http://localhost:9091
          job: pushgateway-demo
          grouping-key:
            key1: value1
          shutdown-operation: push
