spring:
  profiles:
    active: beta
  cloud:
    config:
      profile: ${spring.profiles.active}
      label: master
  config:
    import:
      configserver:http://localhost:8888
  output:
    ansi:
      enabled: always
management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["refresh"]
