spring:
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/tmp/h2_jpa_rest_db1
    username: sa
    password:
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      ddl-auto: update
