spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  session:
    store-type: redis
  output:
    ansi:
      enabled: always
server:
  servlet:
    session:
      cookie:
        max-age: 60s
        name: SPRING_SESSION_REDIS
        secure: false
        http-only: true
      timeout: 60s
