server:
  port: 8081
spring:
  rsocket:
    server:
      address: localhost
      port: 7000
      transport: tcp
  output:
    ansi:
      enabled: always
logging:
  level:
    io.rsocket.FrameLogger: DEBUG
