spring:
  datasource:
    url: jdbc:h2:mem:mybatis-db;NON_KEYWORDS=user
    username: sa
    password:
  output:
    ansi:
      enabled: always
logging:
  level:
    com.example.mapper: debug
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
